# Dockerfile.mock
FROM python:3.11-slim

WORKDIR /app
COPY orchestration/mock_service.py /app/mock_service.py

RUN pip install fastapi uvicorn

RUN pip install fastapi uvicorn nats-py

ENV MOCK_ENDPOINTS "[]"

CMD ["uvicorn", "mock_service:app", "--host", "0.0.0.0", "--port", "80"]
